/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.hks.struts.action;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.han.domain.Pai;
import com.han.domain.User;
import com.han.service.UserService;

/**
 * MyEclipse Struts Creation date: 02-08-2017
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag"
 */
public class FaPaiAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//进入此控制器说明用户点击准备
		// 得到当前已准备用户
		User user = (User) request.getSession().getAttribute("user");
		//如果用户的flag是c  则证明是在游戏中
		if("c".equals(user.getFlag())){
			return mapping.findForward("game");
		}
		user.setFlag("b");
		ArrayList<User> userList = (ArrayList<User>) this.getServlet()
				.getServletContext().getAttribute("userList");
		if (userList == null) {
			userList = new ArrayList<User>();
		}
		userList.add(user);
		this.getServlet().getServletContext()
				.setAttribute("userList", userList);
		//找到当前准备好的三个人(即状态为b的人,状态为c表示在游戏中),并为这三个人分配位置
		User[] preUser=UserService.checkDesk(userList);
		//判断当前准备好的用户个数且当前用户数组上有此用户
		if(preUser!=null&&UserService.checkUserOnPredesk(preUser, user)){
			request.setAttribute("preUser", preUser);
			return mapping.findForward("game");
		}else{
			return  mapping.findForward("ok");
		}
		

	}
}